### PR TITLE
New features and clean up cmake

### PR DESCRIPTION
**Pull request by constantinpape**
I have updated a lot of my distributed stuff and added functionality for on-the-fly affine transformations.
Also cleaned up cmake, fixed some build issues and updated installation instructions in the README.

@DerThorsten travis currently fails with a weird error for me, `undefined symbol: std::allocator<float>::allocator()`, see https://travis-ci.org/constantinpape/nifty/builds/655425639#L1670.
I can't reproduce this locally so I think it's a fluke.

I think it makes sense to merge now despite this to have the updated README and CMake fixes on master, but it's also ok to wait till I fixed the travis issues. I won't have time to look into this in the next two weeks though.

### CODE REVIEW

**Comment by DerThorsten** [comment]
thanks for PR!

**Comment by DerThorsten** [comment]
Nice stuff :)

**Comment by constantinpape** [comment]
> Nice stuff :)

Thanks :).

Unfortunately the travis build is still failing with linker errors `_ZNSaIfEC1Ev`= `std::allocator<float>::allocator()`. I can't reproduce this locally and are a bit puzzled...

Any ideas what the issue might be?

**Comment by DerThorsten** [comment]
Strange shit, maybe some libstdc++ problem (I am blindly guessing here), or maybe just CI noise.
Btw for all new projects I use github actions, very simple to use. Maybe we should switch.

**Comment by constantinpape** [comment]
> Btw for all new projects I use github actions, very simple to use. Maybe we should switch.

Yeah, sounds like a good idea.
Do you have a template for github actions somewhere?

**Comment by DerThorsten** [comment]
The examples/stubs from github are excellent https://github.com/DerThorsten/nifty/actions/new
(new projects are from work, cannot share :/ )

**Comment by constantinpape** [comment]
> The examples/stubs from github are excellent https://github.com/DerThorsten/nifty/actions/new
> (new projects are from work, cannot share :/ )

Thanks, will have a look at it later.

**Comment by constantinpape** [comment]
Fixes #133.

**Comment by constantinpape** [comment]
@DerThorsten ok, I added a first version of the github actions workflow and it's super convenient.
Should we remove travis?

I also figured out the linker error; this happened because it was build with conda compilers, but then runtime linking was done against system libs. There are still some test errors, gonna fix this later.

**Comment by constantinpape** [comment]
> Btw for all new projects I use github actions, very simple to use. Maybe we should switch.

Yeah, sounds like a good idea.
Do you have a template for github actions somewhere?

**Comment by constantinpape** [comment]
Ok, github actions passes now.
I think we should remove travis and appveyor and I can set up a build matrix in github actions eventually to also cover win and mac builds. I would rather merge this PR before that though, what do you think @DerThorsten?

**Comment by DerThorsten** [comment]
Sure lets merge this!

**Comment by DerThorsten** [comment]
great work and thanks for keeping nifty nifty

**Comment by constantinpape** [comment]
> great work and thanks for keeping nifty nifty

Sure ;). 
Gonna look into removing travis / appveyor and setting up build matrix in gh actions in the next couple of days.

**Pull request merged**
