### PR TITLE
Update LP_MP external dependency and rounders for lp-mp

### PR DESCRIPTION
**Pull request by constantinpape**
Change the external LP_MP dependency to Paul's repo and use rvalue references in the rounder functors.

### CODE REVIEW

**Comment by DerThorsten** [comment]
nice

**Comment by DerThorsten** [comment]
@constantinpape  Is this just travis bitching around?
Should I merge?!? Seems like it cannot checkout some commit for paus repo

**Comment by constantinpape** [comment]
@DerThorsten 
I think I know what the issue is here:
I changed the repository of LP_MP from my fork to Paul's version.
Apparently I have done this incorrectly, s.t. these changes are not properly reflected when pushing the updates in the submodule to the remote.

I will fix this tommorow.

**Comment by constantinpape** [comment]
I have fixed the issue and travis checks run through.

**Pull request merged**
