### PR TITLE
use new style find python

### PR DESCRIPTION
**Pull request by hmaarrfk**
See https://cmake.org/cmake/help/latest/module/FindPython.html for more info

and the results of
https://github.com/conda-forge/nifty-feedstock/pull/19

### CODE REVIEW

**Comment by hmaarrfk** [comment]
You might also just want to delete: https://github.com/hmaarrfk/nifty/blob/patch-1/conda-recipe/build.sh.old

**Comment by hmaarrfk** [comment]
Hmm FindVigra and likely most other things from: https://github.com/hmaarrfk/nifty/tree/patch-1/cmake/modules should just be removed. sorry for that noise feel free to force push to revert anything here.

**Review by constantinpape — APPROVED** [review]

**Comment by constantinpape** [comment]
Thanks @hmaarrfk. It looks like the CI is outdated. I will fix this in a separate PR.

**Comment by hmaarrfk** [comment]
great to see this in

**Pull request merged**
