### PR TITLE
Chunked Sliced Rag

### PR DESCRIPTION
**Pull request by constantinpape**
Initial running version of the sliced rag with chunked array labels.

### CODE REVIEW

**Comment by DerThorsten** [comment]
could you try to make it compile on travis again?
(This is why I reverted this again)
Greetings Thorsten

**Comment by constantinpape** [comment]
kk

**Comment by DerThorsten** [comment]
I would assume it is just a missing "libhdf5-serial-dev" in travis (which I just added to my fork)

**Comment by constantinpape** [comment]
Adding "libhdf5-serial-dev" in travis fixes the failing "include hdf5.h", however now there is an issue due to incompatible vigra versions (i am relying on some functionality I have added to the chunked array, which of course is not in your vigra fork yet - should have thoght of that before...) 
Let's have a look at that tomorrow.

**Comment by constantinpape** [comment]
I have separated the headers for the chunked and normal rag for properly separating the stuff depending on hdf5.
Travis build is now working on mac and linux.

**Comment by DerThorsten** [comment]
feel free to make a pr, I'll merge it

**Pull request merged**
