### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ahmadnish**
marray removed from external
.DS_STORE files deleted

### CODE REVIEW

**Comment by ahmadnish** [comment]
I made a docstrings structure just for making sure I am adding them the right way. So the comments are not quite meaningful yet. Let me know if there is something wrong with the structure.

**Comment by ahmadnish** [comment]
Issue #95 fixed.

**Comment by DerThorsten** [comment]
@ahmadnish  as you can see  continuous-integration with travis fails with your
PR.
This means there is still an error in the code. You can look at the Details of travis to see why it fails.

**Comment by ahmadnish** [comment]
@DerThorsten, I guess it's good to go now.

**Pull request merged**
