### PR TITLE
More windows

### PR DESCRIPTION
**Pull request by bluescarni**
Some more windows-oriented modifications, plus enable the compilation of the python bindings in appveyor.

The python bindings do not currently compile due to a series of issues, which can be found at this log:

https://ci.appveyor.com/project/bluescarni/nifty/build/1.0.3/job/w05lgnybx03u7frk#L4177

(MSVC makes a summary of all compilation/linking errors at the end of the build, which is where the link above points to)

Summarizing:

- Unresolved symbols to HDF5 types (I believe):

```console
  hdf5_common.obj : error LNK2001: unresolved external symbol H5P_CLS_FILE_ACCESS_ID_g [C:\projects\nifty\build\src\python\lib\hdf5\_hdf5.vcxproj]
  hdf5_array.obj : error LNK2001: unresolved external symbol H5P_CLS_DATASET_CREATE_ID_g [C:\projects\nifty\build\src\python\lib\hdf5\_hdf5.vcxproj]
  hdf5_array.obj : error LNK2001: unresolved external symbol H5T_IEEE_F64LE_g [C:\projects\nifty\build\src\python\lib\hdf5\_hdf5.vcxproj]
  hdf5_array.obj : error LNK2001: unresolved external symbol H5T_STD_U8LE_g [C:\projects\nifty\build\src\python\lib\hdf5\_hdf5.vcxproj]
  hdf5_array.obj : error LNK2001: unresolved external symbol H5T_STD_U64LE_g [C:\projects\nifty\build\src\python\lib\hdf5\_hdf5.vcxproj]
  hdf5_array.obj : error LNK2001: unresolved external symbol H5T_STD_I16LE_g [C:\projects\nifty\build\src\python\lib\hdf5\_hdf5.vcxproj]
  hdf5_array.obj : error LNK2001: unresolved external symbol H5T_STD_I8LE_g [C:\projects\nifty\build\src\python\lib\hdf5\_hdf5.vcxproj]
  hdf5_array.obj : error LNK2001: unresolved external symbol H5T_STD_I32LE_g 
```

- Various source-level issues in the lp_mp code:

```console
"C:\projects\nifty\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj" (default target) (10) ->
(ClCompile target) -> 
  C:\projects\nifty\externals\LP_MP\external\tclap\include\tclap/StandardTraits.h(145): error C2766: explicit specialization; 'TCLAP::ArgTraits<std::size_t>' has already been defined (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) [C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj]
  C:\projects\nifty\externals\LP_MP\external\meta\include\meta/meta.hpp(621): error C2938: 'invoke<T::type>' : Failed to specialize alias template (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) [C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj]
  C:\projects\nifty\externals\LP_MP\external\meta\include\meta/meta.hpp(621): error C2794: 'invoke': is not a member of any direct or indirect base class of 'meta::v1::id<void>' (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) 
[C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj]
  C:\projects\nifty\externals\LP_MP\external\meta\include\meta/meta.hpp(621): error C2938: 'invoke<meta::v1::id<void>,T::type>' : Failed to specialize alias template (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) [C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj]
  C:\projects\nifty\externals\LP_MP\external\meta\include\meta/meta.hpp(621): error C2938: 'void_<T::type>' : Failed to specialize alias template (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) [C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj]
  C:\projects\nifty\externals\LP_MP\external\meta\include\meta/meta.hpp(624): error C2976: 'meta::v1::detail::is_trait_': too few template arguments (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) [C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj]
  C:\projects\nifty\externals\LP_MP\external\meta\include\meta/meta.hpp(633): error C2903: 'invoke': symbol is neither a class template nor a function template (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) [C:\projects\nifty\build\src\python\lib\graph\optimization\lifted_multicut\_lifted_multicut.vcxproj]
  C:\projects\nifty\externals\LP_MP\external\meta\include\meta/meta.hpp(633): error C3200: 'T::invoke': invalid template argument for template parameter '<unnamed-symbol>', expected a class template (compiling source file C:\projects\nifty\src\python\lib\graph\optimization\lifted_multicut\lifted_multicut_mp.cxx) 
```

There were some additional issues related to the use of ``size_t`` rather than ``std::size_t``, I believe those are fixed with the changes in this PR.

### CODE REVIEW

**Comment by bluescarni** [comment]
Bah I just realised my editor removed a bunch of extra whitespaces/empty lines, increasing the diff :/ Sorry about that.

**Comment by DerThorsten** [comment]
could you make the PR against the dev branch?

And many many thanks!
WITH_LP_MP is highly experimental atm.
But I guess the HDF5 issues should be easy to fix

**Comment by bluescarni** [comment]
I've rebased against ``dev``. Should we disable LP_MP for the time being?

**Comment by bluescarni** [comment]
I think I managed to compile the python bindings without LP_MP and QPBO, the HDF5 issue should be solved. But now my local branch is a mess with the rebasing and I am not sure I can do more progress like this. Probably would be best to merge this immediately into dev and proceed from there.

**Comment by DerThorsten** [comment]
merged....

**Pull request merged**
