### PR TITLE
Subgraph extraction

### PR DESCRIPTION
**Pull request by constantinpape**
Extraction of a subgraph from undirected list graph based on a list of subnodes.

### CODE REVIEW

**Comment by constantinpape** [comment]
This also includes exposing the ufd to python and adding some functionality to it.

**Comment by constantinpape** [comment]
Do you mean the api for the subgraph-extraction?
I guess vectorising makes sense in general, need to have a look at the implementation again though, as changing to marray views in the c++ code won't be totally straightforward without introducing a copy of the data.

**Comment by DerThorsten** [comment]
hubs, I forget to mention that i just talked about the ufd python api.

**Comment by constantinpape** [comment]
I have updated the PR to the newer module structure and also implemented vectorized versions of
ufd::find and ufd::mege.

**Pull request merged**
